name: Leaderboard Count

on:
  push:
  issues:
    types:
      - opened

jobs:
  converter:
    name: Update contribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: convert-yaml-to-json
        with:
          path: './_data/fellows.yml'
          from: 'yaml'
          to: 'json'
      - uses: actions/github-script@v3
        id: increment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fellows = ${{ steps.convert-yaml-to-json.outputs.data }};
            const contributor = fellows.filter((fellow) => {
              return fellow.githubUsername === context.payload.sender.login;
            })[0];
            if(contributor){
              contributor['contributions'] += 1;
            }
            return fellows;
      - run: echo '${{steps.increment.outputs.result}}' > buffer.json
      - uses: fabasoad/yaml-json-xml-converter-action@main
        id: convert-json-to-yaml
        with:
          path: 'buffer.json'
          from: 'json'
          to: 'yaml'
      - run: echo '${{steps.convert-json-to-yaml.outputs.data}}' > _data/fellows.yml
      - uses: EndBug/add-and-commit@v7
        with:
          cwd: ${{env.GITHUB_WORKSPACE}}
          add: _data/fellows.yml